# Generated by Django 3.0.5 on 2020-12-04 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SerialNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=25)),
                ('video_name', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
                ('video_tag', models.CharField(max_length=25)),
                ('publish_date', models.DateField()),
                ('video_ticket', models.IntegerField()),
                ('magnet_url', models.CharField(max_length=255)),
            ],
        ),
    ]
