# Generated by Django 3.0 on 2019-12-18 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('className', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentID', models.CharField(max_length=20)),
                ('subjectID', models.CharField(max_length=20)),
                ('classID', models.CharField(max_length=20)),
                ('score', models.FloatField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('classID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
                ('birthday', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectID', models.IntegerField(primary_key=True, serialize=False)),
                ('subjectName', models.CharField(max_length=20)),
                ('teacherID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('teacherID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('roleID', models.IntegerField(max_length=2)),
            ],
        ),
    ]
