# Generated by Django 3.0 on 2020-01-11 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentManage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChooseSub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectID', models.CharField(max_length=20)),
                ('studentID', models.CharField(max_length=20)),
                ('isChoose', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.FloatField(default=0, max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='roleID',
            field=models.IntegerField(),
        ),
    ]
